name: Build the binary

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    name: Build
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable

      - name: Compile project
        run: cargo build --release

      - name: Rename build
        run: mv target/release/sudoku-solver target/release/$(echo sudoku-solver-${{ runner.os }}-${{ runner.arch }} | tr '[:upper:]' '[:lower:]')

      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mv target/release/sudoku-solver-*
